const mongoose = require('mongoose');
const Schema = mongoose.Schema;
/**
 * Represents a schema for a user's entry storing their code, notes, and details about the LeetCode problem they are solving.
 * Each user entry is associated with a unique Google user ID and contains information essential for tracking their study progress
 * using the SuperMemo algorithm.
 */
const UserEntrySchema = new Schema({
    // Unique identifier for the user from Google OAuth 2.0
    googleId: {
        type: String,
        required: true,
    },
    // User-submitted code for the problem
    code: {
        type: String,
        required: true
    },
    // Notes created by the user or generated by the AI
    notes: {
        type: String,
        required: true
    },
    // Name of the LeetCode problem
    question_name: {
        type: String,
        required: true
    },
    // Full text of the LeetCode question
    question: {
        type: String,
        required: true
    },
    // Timestamp for when the entry was created, defaults to current time
    date: {
        type: Date,
        default: Date.now
    },
    // Easiness factor for the SuperMemo algorithm, starting default at 2.5
    eFactor: {
        type: Number,
        default: 2.5
    },
    // Number of times the problem has been reviewed
    repetition: {
        type: Number,
        default: 0
    },
    // Date when the problem was last reviewed
    lastReviewed: {
        type: Date,
        default: Date.now
    },
    // Date when the problem is scheduled to be reviewed next
    nextReviewDate: {
        type: Date,
        default: Date.now
    },
});

module.exports = UserEntry = mongoose.model('userEntry', UserEntrySchema);
