version: '3.4'

services:
  backend:
    build: ./BackendServices
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/UserEntry
    mem_limit: 500m
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
    volumes:
      - ./Frontend/build:/usr/share/nginx/html
    mem_limit: 500m
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    restart: unless-stopped

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    mem_limit: 500m
    healthcheck:
      test: "echo 'db.runCommand(\"ping\").ok' | mongo localhost:27017/test --quiet"
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
