version: '3'
services:
  backend:
    build: ./BackendServices
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/UserEntry
    depends_on:
      - mongo
  frontend:
    build: ./Frontend
    ports:
      - "3000:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
